name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - run: |
        sudo apt update
        sudo apt install gcc g++

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - run: nix-shell
    
    - name: Run tests
      run: python -m unittest discover tests
